service: aurora

image: northeastprince/aurora

servers:
  web:
    hosts:
      - 5.75.231.239
    labels:
      traefik.http.routers.aurora.rule: Host(`api.auroraalert.cc`)
    options:
      memory: 1g
      cpus: 0.5
  jobs:
    hosts:
      - 5.75.231.239
    cmd: bundle exec sidekiq
    options:
      memory: 1g
      cpus: 1

registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_ENV: production
    DATABASE_HOST: 172.17.0.1
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_PASSWORD
    - REDIS_URL

builder:
  remote:
    arch: amd64
    host: ssh://root@5.75.231.239

accessories:
  pg:
    image: postgres
    host: 5.75.231.239
    port: 5432
    env:
      clear:
        POSTGRES_USER: aurora
        POSTGRES_DB: aurora_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    options:
      memory: 1g
      cpus: 1
  redis-sidekiq:
    image: redis
    host: 5.75.231.239
    port: 6379
    directories:
      - data:/data
    options:
      memory: 512m
      cpus: 0.5

healthcheck: # default is /up on port 3000
  path: /robots.txt
