# Name of your application. Used to uniquely configure containers.
service: aurora

# Name of the container image.
image: northeastprince/aurora

# Deploy to these servers.
servers:
  web:
    hosts:
      - 5.75.231.239
    labels:
      traefik.http.routers.aurora.rule: Host(`api.auroraalert.cc`)
    options:
      memory: 1g
      cpus: 0.5
  jobs:
    hosts:
      - 5.75.231.239
    cmd: bundle exec sidekiq
    options:
      memory: 1g
      cpus: 1

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: ghcr.io
  username:
    - MRSK_REGISTRY_USERNAME
  password:
    - MRSK_REGISTRY_PASSWORD

# Inject ENV variables into containers (secrets come from .env).
env:
  clear:
    RAILS_ENV: production
    DATABASE_HOST: 172.17.0.1
  secret:
    - SECRET_KEY_BASE
    - DATABASE_PASSWORD
    - PRIMARY_ENCRYPTION_KEY
    - DETERMINISTIC_ENCRYPTION_KEY
    - ENCRYPTION_KEY_DERIVATION_SALT
    - REDIS_URL
    - WEATHERAPI_KEY
    - TWILIO_ACCOUNT_SID
    - TWILIO_AUTH_TOKEN
    - TWILIO_MESSAGING_SERVICE_SID
    - APPSIGNAL_PUSH_API_KEY

# Call a broadcast command on deploys.
# audit_broadcast_cmd:
#   bin/broadcast_to_bc

# Use a different ssh user than root
# ssh:
#   user: app

# Configure builder setup.
builder:
  remote:
    arch: amd64
    host: ssh://root@5.75.231.239

# Use accessory services (secrets come from .env).
accessories:
  pg:
    image: postgres
    host: 5.75.231.239
    port: 5432
    env:
      clear:
        POSTGRES_USER: aurora
        POSTGRES_DB: aurora_production
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
    options:
      memory: 1g
      cpus: 1
  redis-sidekiq:
    image: redis
    host: 5.75.231.239
    port: 6379
    directories:
      - data:/data
    options:
      memory: 512m
      cpus: 0.5

# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
healthcheck:
  path: /robots.txt
